### PR TITLE
Added Andre's theme

### PR DESCRIPTION
**Pull request by xaviablaza**

### CODE REVIEW

**Comment by xaviablaza** [comment]
The login page has already been added and routed to the root of the website. Is there anything else that's needed?

**Comment by xaviablaza** [comment]
I've noticed an issue where the email and password placeholder is overlaid after adding values to both fields. Will work on a fix.

**Comment by andreperkins12** [comment]
I'll be adding a Nav Bar

**Comment by xaviablaza** [comment]
@khafa100 Fixed email and password placeholder being overlaid.

**Pull request merged**
